name: Deploy to Github Pages

on:
  push:
    branches:
      - 'pages/demo'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'pages/demo'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.14.2'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload production build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
          overwrite: true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download production build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./dist
          publish_branch: test
